### ISSUE TITLE
save scroll memory in other hook

### ISSUE THREAD

**Issue by villander** [ef4/memory-scroll#2]
@ef4 i have a app with `messenger` but my component `message-list` not is destroyed when there is change conversation. Then think that your addon `memory-scroll` could have one more approach to save scroll state beyond the hook `willDesroyElement`. Because we have several scenarios in the real world that we do  not need destroy our components.

My suggestion is:

``` javascript

{{#memory-scroll 
     memoryEvent='onScroll' // default 'onDestroy'
     key='conversationId' }}
{{/memory-scroll}}


export default Ember.Component.extend({
  memory: Ember.inject.service('memory-scroll'),

  didInsertElement() {
    if (this.get('memoryEvent') === 'onScroll') {
      this.$().on('scroll', this, this.onScroll.bind(this));
    }
  },

  onScroll() {
   this.remember(this.get('key'));
  },

  didRender() {
    let key = this.get('key');
    if (!key) {
      throw new Error("You must provide a key to memory-scroll like {{memory-scroll key=\"my-awesome-pane\"}}.");
    }
    if (key !== this._lastKey) {
      this.remember(this._lastKey);
      this._lastKey = key;
      this.restore(key);
    }
  },

  willDestroyElement() {
    if (this.memoryEvent === 'onScroll') {
      this.$().off('scroll', this, this.onScroll.bind(this));
    } else {
      this.remember(this.get('key'));
    }
  },

....

});


```

I'll submit a pull request

**Comment by ef4** [comment]
I think `memory-scroll` already does what you need as long as your ensure the key is changing when the data is changing.

You may need to change `key='conversationId'` to `key=conversationId` (or `key=conversation.id` or whatever real key you have available in your component).

I often make keys like:

``` hbs
key=(concat "message-list" conversation.id)
```

so that it is unique based on both the name of the component and the individual model.

**Comment by villander** [comment]
@ef4 you do not understand, my component is long life. It is never destroyed and its scroll addon is saved only on the hook `willDestroyElement`. Then I'll need to save every time you make a scroll on page.

Look my PR #3 

https://github.com/ef4/memory-scroll/blob/master/addon/components/base.js#L18

**Comment by ef4** [comment]
It will also remember [here in the didRender hook](https://github.com/ef4/memory-scroll/blob/5188b1e7504247f222983ce2b79c3d015e4d7b72/addon/components/base.js#L12).

`didRender` will run every time the key changes.

**Comment by villander** [comment]
Yeeeaah @ef4 i was wrong , for some time it did not work for me. Now ok

Thanks!

**Comment by villander** [comment]
@ef4 how i makes to makes `extend` of  `didRender` on `memory-scroll` ? I need use `didRender` to handle other things in my app

**Comment by ef4** [comment]
You can extend like:

``` js
import MemoryScroll from 'memory-scroll/components/memory-scroll';
export default MemoryScroll.extend({
  didRender() {
    this._super();
    // your stuff here
  }
});
```

But it's often better to use composition over inheritance and introduce separate components for separate concerns.

**Comment by villander** [comment]
Good!
@ef4 how make composition with Ember.object ?
I do not found anything like

**Comment by ef4** [comment]
I mean that instead of extending a component to make it do many things, it is better to nest separate components, like:

``` hbs
{{#memory-scroll}}
  {{#your-other-component-here}}
    ...
  {{/your-other-component-here}}
{{/memory-scroll}}
```

**Comment by villander** [comment]
Thanks @ef4
