### ISSUE TITLE
{{remember-document-scroll}} updates scrollTop before model is resolved

### ISSUE THREAD

**Issue by taras** [ef4/memory-scroll#4]
I'm not 100% about this, but it seems that scrollTop is being updated as soon as the URL changes but before the model is resolved. 

Can you think of any reason why this might be happening?

**Comment by villander** [comment]
@taras the scroll is `restored` when the `didRender` is fired.  Look this https://github.com/ef4/memory-scroll/blob/master/addon/components/base.js#L11

To evaluate model, must be a `didReceiveAttrs` for example.
Why you need updated scroll when model is solved?

I think that we can make a improve in this addon. Can you tell me more about you case?

**Comment by villander** [comment]
@taras your model seems be a `ObjectProxy`. So you can use:

``` javascript
{{#if model.isFulfilled}}
  {{memory-scroll key=model.id}}
{{/if}}
```

**Comment by villander** [comment]
This issue it is being closed for lack of response.
If you come back, we will open @taras

**Comment by taras** [comment]
@villander hey, sorry I didn't get back to you. It slipped through the cracks of my inbox. Let me look at this and I'll write back if the above doesn't resolve my problem.

**Comment by villander** [comment]
Ok @taras anything you can come back with a twiddle for me to help you better :D

**Comment by villander** [comment]
I'm closing this issue for lack of evidence
